pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = 'my56k8s.jfrog.io/sample-docker-local'
        APP_IMAGE = 'ci-pipeline-app'
        RUNNER_IMAGE = 'github-runner'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        CLUSTER_NAME = "my-cluster"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: "main",
                    url: 'https://github.com/turkardiksha345-oss/docker-ci-with-jenkins-jfrog.git'
            }
        }

        stage('Build Runner Image') {
            steps {
                sh '''
                docker build -t $RUNNER_IMAGE:$IMAGE_TAG ./docker/runners
                docker tag $RUNNER_IMAGE:$IMAGE_TAG $DOCKER_REGISTRY/$RUNNER_IMAGE:$IMAGE_TAG
                docker tag $RUNNER_IMAGE:$IMAGE_TAG $DOCKER_REGISTRY/$RUNNER_IMAGE:latest
                '''
            }
        }

        stage('Build App Image') {
            steps {
                sh '''
                docker build -t $APP_IMAGE:$IMAGE_TAG -f docker/Dockerfile .
                docker tag $APP_IMAGE:$IMAGE_TAG $DOCKER_REGISTRY/$APP_IMAGE:$IMAGE_TAG
                docker tag $APP_IMAGE:$IMAGE_TAG $DOCKER_REGISTRY/$APP_IMAGE:latest
                '''
            }
        }

        stage('Push Images to JFrog') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'jfrog-creds',
                    usernameVariable: 'JFROG_USER',
                    passwordVariable: 'JFROG_PASSWORD'
                )]) {
                    sh '''
                    echo $JFROG_PASSWORD | docker login my56k8s.jfrog.io -u $JFROG_USER --password-stdin

                    docker push $DOCKER_REGISTRY/$RUNNER_IMAGE:$IMAGE_TAG
                    docker push $DOCKER_REGISTRY/$RUNNER_IMAGE:latest

                    docker push $DOCKER_REGISTRY/$APP_IMAGE:$IMAGE_TAG
                    docker push $DOCKER_REGISTRY/$APP_IMAGE:latest
                    '''
                }
            }
        }

        stage('Load Image to KIND') {
            steps {
                sh '''
                echo "📦 Loading image into KIND..."

                if command -v kind >/dev/null 2>&1; then
                    kind load docker-image $APP_IMAGE:$IMAGE_TAG --name $CLUSTER_NAME
                else
                    echo "❌ KIND not installed"
                    exit 1
                fi
                '''
            }
        }

        stage('Deploy App to Kubernetes') {
            steps {
                sh '''
                echo "🚀 Deploying app..."

                ls -R

                kubectl apply -f ./kind-cluster/app-deployment.yaml

                kubectl set image deployment/ci-app \
                app=$APP_IMAGE:$IMAGE_TAG --record
                '''
            }
        }

        stage('Deploy Runner to Kubernetes') {
            steps {
                sh '''
                echo "🚀 Deploying runner..."

                kubectl apply -f ./kind-cluster/runner-deployment.yaml
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully"
        }
        failure {
            echo "❌ Pipeline failed"
        }
    }
}