apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-app
  template:
    metadata:
      labels:
        app: ci-app
    spec:
      containers:
        - name: app
          image: ci-pipeline-app:8
          ports:
            - containerPort: 3000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: ci-app-service
spec:
  type: NodePort
  selector:
    app: ci-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
